# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7560278893c62c5f7538d8dae72815b713bed5b003b397b45c00fb6761bb2e23a1a92c1b5965a01a81ff7dc101e2f728f24ad8c83a3cac6bcc8bf3d8ba7a861

test:
  secret_key_base: 09d935903d83585ba4c6d8757b1512cd6b5db9b86063752ec8f47aeceea5ce5b93a0af9398a29e44479156f9c95673061c510bb486cf8cb55881076c0e9d57c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
